fix(api): Fixed getFullBaseURL method
InspectorIncognito/gtfs-editor-frontend pull request #9
Opened 2024-12-26 13:11 UTC by Mrtn-fa

# 📚Context
The service selector inside of Trip builder appears to load forever. This is caused by a wrong api call.

# 📝Changes
- Fixed getFullBaseURL to the base api class.

# 🔍Testing
N/A

# 📝Pending/Future Work
N/A

2024-12-26 13:19 UTC, DiegoTGJ requested changes
Agregemos tests para el comportamiento

2025-01-06 19:28 UTC, DiegoTGJ requested changes
Faltan tests igual

2025-01-06 19:28 UTC, DiegoTGJ commented on src/api/httpClient.js
> +    baseURL: `${baseUrl}/${apiEndpoint}`,
Va a pasar lo mismo que antes cuando no exista el VUE_APP_BASE_URL

2025-01-21 12:19 UTC, joelriquelme requested changes

2025-01-21 12:19 UTC, joelriquelme commented on cypress/e2e/createGTFS.cy.js
> +    */
Se te quedó un comentario gigante aquí, es muy necesario?

2025-01-21 15:28 UTC, Cotorrra commented on cypress/e2e/createGTFS.cy.js
> +    */
(same question)

2025-01-22 14:40 UTC, joelriquelme approved these changes
LGTM

2025-01-22 14:40 UTC, merged